### ISSUE TITLE
Load widget in standalone mode

### ISSUE THREAD

**Issue by hhkaos** [gavinr/web-appbuilder-tools-techniques-dev-summit-2016#3]
Hi @gavinr & @tomwayson ,

How did you load the widget in standalone mode for development?, if I don't recall badly you did it [at the end of the talk](http://gavinr.github.io/web-appbuilder-tools-techniques-dev-summit-2016/#/42), I'm looking in the [documentation page](https://developers.arcgis.com/web-appbuilder/guide/xt-welcome.htm) but I don't find it.

Thanks!

**Comment by tomwayson** [comment]
What I showed was a Dojo widget (not a Web AppBuilder widget) that I created using [yo esri-widget](https://github.com/tomwayson/generator-esri-widget). The esri-widget generator creates a test page, and you can serve that page from any web server to develop in "standalone mode."

This is not a feature of the Web AppBuilder, and therefore would not be in the documentation.

Ultimately to get any widget you create using that generator into the Web AppBuilder, you would have to also [create a Web AppBuilder widget that would wrap it](http://gavinr.github.io/web-appbuilder-tools-techniques-dev-summit-2016/#/37).

**Comment by hhkaos** [comment]
Ahhh, okok, I didn't get that part :). Thanks :dancer:
